# Copy and move this file to manifests/ghcr-secret.yaml. Update it with your Github Personal Access Token.
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: ghcr-auth
stringData:
  .dockerconfigjson: {"auths":{"ghcr.io":{"auth":"##ReplaceMe##"}}}
