apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg
data:
    region: "eu-central-1"
    dynamodb_tenants_table_name: dev-tenants
    dynamodb_auth_info_table_name: dev-auth-info
    dynamodb_silo_config_table_name: dev-silo-config
    dynamodb_connections_table_name: dev-connections

