apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saas-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:554897346438:certificate/44b80e4f-1254-495c-b62a-4b95ad109448
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-path: /ping
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    external-dns.alpha.kubernetes.io/hostname: admin-dev.devpie.io, api-dev.devpie.io
  labels:
    app: traefik
spec:
  ingressClassName: alb
  rules:
     - http:
        paths:
          - path: /
            backend:
              service:
                name: traefik
                port:
                  number: 443
            pathType: Prefix
