apiVersion: apps/v1
kind: Deployment
metadata:
  name: mic-project
spec:
  selector:
    matchLabels:
      app: mic-project
  template:
    metadata:
      labels:
        app: mic-project
        pod: requires-rds
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - image: ghcr.io/devpies/project:a7e34e3
          name: mic-project
          ports:
            - containerPort: 4004
          imagePullPolicy: Always
          env:
            - name: PROJECT_WEB_PRODUCTION
              value: "true"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws.secrets
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws.secrets
                  key: aws_secret_access_key
            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  name: cfg
                  key: region
            - name: PROJECT_WEB_PORT
              value: "4004"
            - name: PROJECT_COGNITO_USER_POOL_ID
              valueFrom:
                secretKeyRef:
                  name: cognito.secrets
                  key: shared_user_pool_id
            - name: PROJECT_COGNITO_REGION
              valueFrom:
                configMapKeyRef:
                  name: cfg
                  key: region
            - name: PROJECT_NATS_ADDRESS
              value: "nats-svc"
            - name: PROJECT_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres.secrets
                  key: postgres_hostname_projects
            - name: PROJECT_DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres.secrets
                  key: postgres_username_projects
            - name: PROJECT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres.secrets
                  key: postgres_password_projects
---
apiVersion: v1
kind: Service
metadata:
  name: mic-project-svc
spec:
  selector:
    app: mic-project
  ports:
    - port: 4004
      targetPort: 4004