apiVersion: v1
kind: Secret
metadata:
  name: secrets
stringData:

  admin_user_pool_id: "##ReplaceMe##"

  admin_user_pool_client_id: "##ReplaceMe##"

  shared_user_pool_id: "##ReplaceMe##"

  aws_access_key: "##ReplaceMe##"

  aws_secret_access_key: "##ReplaceMe##"

  db_hostname_users: "##ReplaceMe##"
  db_username_users: "##ReplaceMe##"
  db_password_users: "##ReplaceMe##"

  db_hostname_admin: "##ReplaceMe##"
  db_username_admin: "##ReplaceMe##"
  db_password_admin: "##ReplaceMe##"

  db_hostname_projects: "##ReplaceMe##"
  db_username_projects: "##ReplaceMe##"
  db_password_projects: "##ReplaceMe##"
---
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: ghcr-auth
stringData:
  .dockerconfigjson: {"auths":{"ghcr.io":{"auth":""}}}
