apiVersion: apps/v1
kind: Deployment
metadata:
  name: mic-users-depl
spec:
  selector:
    matchLabels:
      app: mic-users
  template:
    metadata:
      labels:
        app: mic-users
    spec:
      containers:
        - image: ghcr.io/devpies/mic-users:76b9f69
          name: mic-users
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "250m"
              memory: "250Mi"
          env:
            - name: API_WEB_PORT
              value: ":4000"
            - name: API_WEB_CORS_ORIGINS
              value: "https://localhost:3000, https://devpie.local"
            - name: API_WEB_AUTH_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: auth0-domain
            - name: API_WEB_AUTH_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: auth0-audience
            - name: API_DB_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: qa-mic-db-users-username
              - name: API_DB_NAME
                valueFrom:
                  secretKeyRef:
                    name: secrets
                    key: qa-mic-db-users-database-name
              - name: API_DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: secrets
                    key: qa-mic-db-users-password
              - name: API_DB_HOST
                valueFrom:
                  secretKeyRef:
                    name: secrets
                    key: qa-mic-db-users-host
            - name: API_NATS_URL
              value: "nats://nats-svc:4222"
            - name: API_NATS_CLIENT_ID
              value: "mic-users"
            - name: API_NATS_CLUSTER_ID
              value: "devpie-client"
            - name: API_WEB_AUTH_M_2_M_CLIENT
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: auth0-m2m-client
            - name: API_WEB_AUTH_M_2_M_SECRET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: auth0-m2m-secret
            - name: API_WEB_AUTH_MAPI_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: auth0-mapi-audience
            - name: API_WEB_SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: sendgrid-api-key
      initContainers:
        - name: schema-migration
          image: devpies/mic-db-users-migration:v000001
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: qa-mic-db-users-url
          command: ["migrate"]
          args:
            ["-path", "/migrations", "-verbose", "-database", "$(DB_URL)", "up"]
---
apiVersion: v1
kind: Service
metadata:
  name: mic-users-svc
spec:
  selector:
    app: mic-users
  ports:
    - port: 4000
      targetPort: 4000
